name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "container/**"
defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build

      - uses: chrislennon/action-aws-cli@1.1
      - run: aws s3 sync dist s3://${{ secerts.AWS_S3_BUCKET_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secerts.AWS_ACCESS_KEY_ID }}
          AWS_SECERT_ACCESS_KEY: ${{ secerts.AWS_SECERT_ACCESS_KEY }}